<?php

/**
 * @file
 * Primary module hooks for aleevas_experements module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function MYTHEME_theme() {
  return [
    'als_exp_template' => [
      'variables' => [
        'items' => NULL,
      ],
      'template' => 'templates/aleevas-template',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function aleevas_experements_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'aleevas_experements/local.library';
}
