filter_settings.ae_filter:
  type: filter
  label: 'Aleevas filter filter'
  mapping:
    example:
      type: string
      label: The Big Brother filter

block.settings.aleevas_experements_contact_form_in_modal:
  type: block_settings
  label: 'Contact form in modal block'
  mapping:
    foo:
      type: string
      label: Foo
